import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headerss from "./Component/Headerss";
import Footer from "./Component/Footer";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistMono} ${GeistSans} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <Headerss/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
